import homeIcon from "./../../../public/icons/home.svg";
import homeActive from "./../../../public/icons/home-active.svg";
import createTweet from "./../../../public/icons/create-tweet.svg";
import logo from "./../../../public/icons/logo.svg";
import messagesActive from "./../../../public/icons/messages-active.svg";
import messages from "./../../../public/icons/messages.svg";
import notificationsActive from "./../../../public/icons/notifications-active.svg";
import notifications from "./../../../public/icons/notifications.svg";
import searchActive from "./../../../public/icons/search-active.svg";
import search from "./../../../public/icons/search.svg";
import close from "./../../../public/icons/close.svg";
import switchIcon from "./../../../public/icons/switch.svg";
import bookmarksIcon from "./../../../public/icons/bookmarks.svg";
import bookmarksActiveIcon from "./../../../public/icons/bookmarks-active.svg";
import listActiveIcon from "./../../../public/icons/lists-active.svg";
import listsIcon from "./../../../public/icons/lists.svg";
import profileActiveIcon from "./../../../public/icons/profile-active.svg";
import profileIcon from "./../../../public/icons/profile.svg";
import topicsIcon from "./../../../public/icons/topics.svg";
import twitterCircleIcon from "./../../../public/icons/twitter-circle.svg";
import accordionChevron from "./../../../public/icons/accordion-chevron.svg";
import more from "./../../../public/icons/more.svg";
import reply from "./../../../public/icons/reply.svg";
import retweet from "./../../../public/icons/retweet.svg";
import like from "./../../../public/icons/like.svg";
import share from "./../../../public/icons/share.svg";
import tweet from "./../../../public/icons/tweet.svg";
import back from "./../../../public/icons/back.svg";
import sun from "./../../../public/icons/sun.svg";
import moon from "./../../../public/icons/moon.svg";

export const HomeIcon = homeIcon;
export const HomeActiveIcon = homeActive;
export const CreateTweetIcon = createTweet;
export const LogoIcon = logo;
export const MessagesActiveIcon = messagesActive;
export const MessagesIcon = messages;
export const NotificationsActiveIcon = notificationsActive;
export const NotificationsIcon = notifications;
export const SearchActiveIcon = searchActive;
export const SearchIcon = search;
export const CloseIcon = close;
export const SwitchIcon = switchIcon;
export const BookmarksIcon = bookmarksIcon;
export const BookmarksActiveIcon = bookmarksActiveIcon;
export const ListActiveIcon = listActiveIcon;
export const ListsIcon = listsIcon;
export const ProfileActiveIcon = profileActiveIcon;
export const ProfileIcon = profileIcon;
export const TopicsIcon = topicsIcon;
export const TwitterCircleIcon = twitterCircleIcon;
export const AccordionChevron = accordionChevron;
export const More = more;
export const Reply = reply;
export const Retweet = retweet;
export const Like = like;
export const Share = share;
export const Tweet = tweet;
export const Back = back;
export const Sun = sun;
export const Moon = moon;
